### PR TITLE
fix: `Burn` and `Recover` msgs public key checks and cli commands

### PR DESCRIPTION
**Pull request by g-luca**
This PR addresses 2 issues in the upgraded implementation of the `Burn` and `Recover` messages:
 - Fixes the missing `pub_key` parameter in the CLI commands for both messages
 - Introduces a validation to check for `nil` values of the `pub_key` in the `msg_server.go`

### CODE REVIEW

**Comment by g-luca** [comment]
Hey @gislik , the pr is ready for your review whenever you want 😄

**Review by gislik — APPROVED** [review]
Looks good 😊 

I'm approving and I'll merge but I have one question, whether it makes sense to differentiate between invalid public keys and missing public keys?

I'll leave the decision up to you for a future PR if you think it's relevant.

**Comment by g-luca** [comment]
@gislik after all it's mostly about UX for the user/dev to determine the issue when the transaction fails. I think `invalid` should be enough to cover it, but if you prefer to distinguish between `invalid` and `missing` I'm happy to make that change, it's only a 3-line change :smile:

**Comment by gislik** [comment]
I think it´s fine as is. I'm just trying to identify "rabbit holes", i.e. places where you spend more time debugging than you like to admit because you assume that the issue is one thing (signatures and their verification can be notoriously hard to get right) when the real issue is something much, much simpler (like the public key is just missing all together).

We'll always have the option of upgrading at a later stage if this becomes a real issue. So good to go 🚀

**Pull request merged**
